### ISSUE TITLE
OLD Time Format works strangely

### ISSUE THREAD

**Issue by Maxetto** [Trojmans/RealTime#2]
So, I'm not using NEW format since I read it's broken.
However OLD Time format is working really strange.
It's good from 12am to 12pm (12-24), after 12am (24) the sun goes into 12pm (12) position and goes backwards to 12am (24).
Sun is always rising and fading on east.
Results are that I have daylight from 12am to 12pm (24-12) and nightime from 12pm to 12am (12-24).

Also, I found that GeoIP uses regionCodes, not regions, therefore if you have a country with more regions, it's impossible to find timezone and the result is a huge NPE spam.

Thank you, I hope for a prompt fix.

P.S. My Timezone is GMT+1

**Comment by Maxetto** [comment]
Fixed by myself by using:
if(time < 0)
  time = 24000 + time;

**Comment by Trojmans** [comment]
I will take a look at it when i have access to my fathers laptop
