### ISSUE TITLE
Using fallback country when connecting from localhost

### ISSUE THREAD

**Issue by Trojmans** [Trojmans/RealTime#4]
When you connect from localhost your IP is shown as "127.0.0.1". The database will of course not know this IP address and is going to use the fallback country. This is a problem when you have a different timezone than the fallback country.

**Comment by Maxetto** [comment]
This is not an issue. If you're connecting with localhost it means you have access to the machine. It's rare if not impossible to have a different country than the fallback one.
Also, FallbackCountry is configurable.
